#!/bin/bash


_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Tepthon" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlcHRob24tYXJhYmljL1RlcHRob24vYXJjaGl2ZS9tYXN0ZXIuemlw==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlcHRob24tYXJhYmljL1RlcHRob24vYXJjaGl2ZS9tYXN0ZXIuemlw==" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Tepthon" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3RlcHRob24tYXJhYmljL1RlcHRob24uZ2l0" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3RlcHRob24tYXJhYmljL1RlcHRob24uZ2l0" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_catpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/tepthon-arabic/Tepthon"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_cat_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="Tepthon.zip"
    echo "جاري تنزيل اكواد السورس "
    wget -q $(_get_ziplink) -O "$zippath"
    echo " تفريغ البيانات "
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo " تم التفريغ "
    echo " يتم التنظيف "
    rm -rf "$zippath"
    sleep 5
    _run_catpack_git
    cd $CATPATH
    _run_cat_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    جار بدء تيبثون    "
    echo "
        "\n",
        "def run():\n",
        "    try:\n",
        "        if None in (SESSION, API_ID, API_HASH, BOT_TOKEN, REDIS_URI, REDIS_PASSWORD) and contains_value(0, env_stats):\n",
        "            print(\"! لم يتم تعيين المتغيرات بشكل يدوي\")\n",
        "            print(\"! قسم تعيين المتغيرات فارغ قم بملئ اماكن الادخال\")\n",
        "        elif not None in (SESSION, API_ID, API_HASH, BOT_TOKEN, REDIS_URI, REDIS_PASSWORD) and contains_value(0, env_stats):\n",
        "            print(\"! تم تعيين المتغيرات بشكل يدوي\")\n",
        "            print(\"...env جاري انشاء ملف\")\n",
        "            env_content = f\"\"\"API_ID={API_ID}\n",
        "API_HASH={API_HASH}\n",
        "SESSION={SESSION}\n",
        "BOT_TOKEN={BOT_TOKEN}\n",
        "REDIS_URI={REDIS_URI}\n",
        "REDIS_PASSWORD={REDIS_PASSWORD}\n",
        "\"\"\"\n",
        "            with open('env', 'w') as file:\n",
        "                file.write(env_content)\n",
        "\n",
        "            os.system(\"rm -rf ./Tepthon/.env && cp env ./Tepthon/.env\")\n",
        "            print(\"env تم تعيين ملف\")\n",
    "
    python3 -m Tepthon
}

_set_bot
